[workspace]
members = ["exercicio_aula06", "exercicio_aula08"] 
default-members = ["exercicio_aula08"] 
resolver = "2"
# executar ou buildar 1 proj. pelo name do pacote, ex: -> cargo build --bin aula4 